services:
  # Memcached для хранения данных о rate-limits
  memcached:
    image: memcached:latest
    networks:
      - 1min-relay-network
    restart: unless-stopped
    # Не требуется экспортировать порт, используется только для внутренней коммуникации
    environment:
      - MEMCACHED_HOST=memcached
      - MEMCACHED_PORT=11211
  
  # 1min-relay
  1min-relay:
    image: kokofixcomputers/1min-relay:latest
    container_name: 1min-relay-container
    ports:
      - "5001:5001"
    networks:
      - 1min-relay-network
    depends_on:
      - memcached
    environment:
      # Используйте строку с разделителями-запятыми для SUBSET_OF_ONE_MIN_PERMITTED_MODELS
      - SUBSET_OF_ONE_MIN_PERMITTED_MODELS=mistral-nemo,gpt-4o-mini,deepseek-chat
      # Установите значение "True" или "False" для PERMIT_MODELS_FROM_SUBSET_ONLY
      - PERMIT_MODELS_FROM_SUBSET_ONLY=False
      # Параметры подключения к Memcached
      - MEMCACHED_HOST=memcached
      - MEMCACHED_PORT=11211
    restart: unless-stopped

networks:
  1min-relay-network:  # Определение пользовательской сети
